// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBthPoIaQM6vBga2jVERWuckeHa-kASdhc',
    appId: '1:1060666283888:web:c6215c4723335751e0e1b5',
    messagingSenderId: '1060666283888',
    projectId: 'kbdailydev',
    authDomain: 'kbdailydev.firebaseapp.com',
    databaseURL: 'https://kbdailydev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kbdailydev.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBthPoIaQM6vBga2jVERWuckeHa-kASdhc',
    appId: '1:1060666283888:web:c6215c4723335751e0e1b5',
    messagingSenderId: '1060666283888',
    projectId: 'kbdailydev',
    authDomain: 'kbdailydev.firebaseapp.com',
    databaseURL: 'https://kbdailydev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kbdailydev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxheU4x6df6pFeNxy7BFeC-8CKJ70qd2M',
    appId: '1:1060666283888:android:e67a38a14355ababe0e1b5',
    messagingSenderId: '1060666283888',
    projectId: 'kbdailydev',
    databaseURL: 'https://kbdailydev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kbdailydev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9EQibcyhlycoJeU4XtFX2aL8aPc8DDrA',
    appId: '1:1060666283888:ios:86c66a8973525c0de0e1b5',
    messagingSenderId: '1060666283888',
    projectId: 'kbdailydev',
    databaseURL: 'https://kbdailydev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kbdailydev.firebasestorage.app',
    iosBundleId: 'com.example.dailyDevDrills',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9EQibcyhlycoJeU4XtFX2aL8aPc8DDrA',
    appId: '1:1060666283888:ios:86c66a8973525c0de0e1b5',
    messagingSenderId: '1060666283888',
    projectId: 'kbdailydev',
    databaseURL: 'https://kbdailydev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kbdailydev.firebasestorage.app',
    iosBundleId: 'com.example.dailyDevDrills',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBthPoIaQM6vBga2jVERWuckeHa-kASdhc',
    appId: '1:1060666283888:web:7c48838e2d6850bbe0e1b5',
    messagingSenderId: '1060666283888',
    projectId: 'kbdailydev',
    authDomain: 'kbdailydev.firebaseapp.com',
    databaseURL: 'https://kbdailydev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kbdailydev.firebasestorage.app',
  );
}
